services:
  redis:
    image: redis:latest
    env_file:
      - ./docker.env
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis_data:/data

  web:
    build: .
    image: rbmanager:latest  # Nome da imagem para o seu aplicativo Django
    env_file:
      - ./docker.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 0.0.0.0:80:8000
    volumes:
      - ./src:/srv:delegated
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
