# Generated by Django 4.2.13 on 2024-06-17 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True, verbose_name='Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fazenda', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True, verbose_name='Movimentação')),
            ],
        ),
        migrations.CreateModel(
            name='Totais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('total_entrada', models.IntegerField(default=None, null=True)),
                ('total_saida', models.IntegerField(default=None, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.animal')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('total', models.FloatField(default=None, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.animal')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Quantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Data')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('entrada', models.IntegerField(blank=True, default=0, null=True, verbose_name='Entrada')),
                ('saida', models.IntegerField(blank=True, default=0, null=True, verbose_name='Saida')),
                ('obs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('animal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.animal')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.fazenda')),
                ('tipo_movimento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.movimento')),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, null=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('nr_nota', models.IntegerField(verbose_name='Numero NF-e')),
                ('data', models.DateField(blank=True, verbose_name='Data')),
                ('entrada', models.DecimalField(decimal_places=2, default='0.00', max_digits=19, verbose_name='Entrada')),
                ('saida', models.DecimalField(decimal_places=2, default='0.00', max_digits=19, verbose_name='Saida')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rebanho.fazenda')),
            ],
        ),
    ]
