# Generated by Django 4.2.13 on 2024-06-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebanho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='fazenda',
        ),
        migrations.RemoveField(
            model_name='totais',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='totais',
            name='fazenda',
        ),
        migrations.DeleteModel(
            name='Financeiro',
        ),
        migrations.DeleteModel(
            name='Saldo',
        ),
        migrations.DeleteModel(
            name='Totais',
        ),
    ]
