# Generated by Django 4.2.13 on 2024-06-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebanho', '0002_remove_saldo_animal_remove_saldo_fazenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidade',
            name='data',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
    ]
